using System.Text;
using System.Reflection;

namespace MLVScan.Tools.SchemaGen;

internal sealed class TypeScriptDefinitionBuilder
{
    private readonly IReadOnlyList<Type> _objectTypes;
    private readonly IReadOnlyList<StringUnionSpec> _stringUnions;
    private readonly NullabilityInfoContext _nullabilityContext = new();

    public TypeScriptDefinitionBuilder(IReadOnlyList<Type> objectTypes, IReadOnlyList<StringUnionSpec> stringUnions)
    {
        _objectTypes = objectTypes;
        _stringUnions = stringUnions;
    }

    public string Build()
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by MLVScan.SchemaGen. Do not edit manually.");
        builder.AppendLine();

        foreach (var stringUnion in _stringUnions)
        {
            WriteStringUnion(builder, stringUnion);
        }

        foreach (var type in _objectTypes)
        {
            WriteInterface(builder, type);
        }

        return builder.ToString();
    }

    private void WriteStringUnion(StringBuilder builder, StringUnionSpec stringUnion)
    {
        if (stringUnion.Name == "SchemaVersion")
        {
            builder.AppendLine($"export const MLVSCAN_SCHEMA_VERSION = '{stringUnion.Values[0]}' as const");
            builder.AppendLine("export type SchemaVersion = typeof MLVSCAN_SCHEMA_VERSION");
            builder.AppendLine();
            return;
        }

        var unionValues = string.Join(" | ", stringUnion.Values.Select(static value => $"'{value}'"));
        builder.AppendLine($"export type {stringUnion.Name} = {unionValues}");
        builder.AppendLine();
    }

    private void WriteInterface(StringBuilder builder, Type type)
    {
        builder.AppendLine($"export interface {SchemaTypeConventions.GetSchemaTypeName(type)} {{");

        foreach (var property in SchemaTypeConventions.GetSchemaProperties(type))
        {
            WriteProperty(builder, property);
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private void WriteProperty(StringBuilder builder, PropertyInfo property)
    {
        var isNullable = SchemaTypeConventions.IsNullableProperty(property, _nullabilityContext);
        var propertyType = BuildNonNullableType(property.PropertyType, property);

        if (isNullable)
        {
            propertyType += " | null";
        }

        builder.AppendLine($"  {SchemaTypeConventions.GetJsonPropertyName(property)}{(isNullable ? "?" : string.Empty)}: {propertyType}");
    }

    private string BuildNonNullableType(Type type, PropertyInfo? property = null)
    {
        var nonNullableType = Nullable.GetUnderlyingType(type) ?? type;

        if (property != null && SchemaTypeConventions.GetStringUnion(property) is { } stringUnion)
        {
            return stringUnion.Name;
        }

        if (nonNullableType == typeof(string))
        {
            return "string";
        }

        if (nonNullableType == typeof(bool))
        {
            return "boolean";
        }

        if (nonNullableType == typeof(int) || nonNullableType == typeof(long) || nonNullableType == typeof(float) ||
            nonNullableType == typeof(double) || nonNullableType == typeof(decimal))
        {
            return "number";
        }

        if (SchemaTypeConventions.IsCollectionType(nonNullableType))
        {
            return $"{BuildNonNullableType(SchemaTypeConventions.GetCollectionElementType(nonNullableType))}[]";
        }

        if (SchemaTypeConventions.IsDictionaryType(nonNullableType))
        {
            return $"Record<string, {BuildNonNullableType(nonNullableType.GetGenericArguments()[1])}>";
        }

        if (SchemaTypeConventions.IsSchemaObjectType(nonNullableType))
        {
            return SchemaTypeConventions.GetSchemaTypeName(nonNullableType);
        }

        throw new NotSupportedException($"TypeScript generation does not support CLR type '{nonNullableType.FullName}'.");
    }
}
